### ISSUE TITLE
RemoveAsync by Id

### ISSUE THREAD

**Issue by fructuoso** [Avanade/Liquid-Application-Framework#41]
In the current implementation of **Liquid.Repository**, it’s necessary call function **FindById** then call function **RemoveAsync**.
Could we implement a function to remove by Id? Because it would simplify the implementation.

**Comment by lucianareginalino** [comment]
To solve this, in an internal discussion by the team of maintainers of the framework, we understand that the solution should be:

- change method RemoveAsync(TEntity entity) to RemoveByIdAsync(TIdentifier id), in main Repository interface (ILightRepository).
- Extend the main interface for creating methods that enable the use of partition key in cartridge implementations for NoSQL databases providers, since methods such as RemoveAsync and FindById as they are implemented can generate a crosspartition reading, which raises the costs of application.
proposed extension methods:
    Task<IEnumerable<TEntity>> WhereAsync(Expression<Func<TEntity, bool>> whereClause);
    Task FindByPartitionAsync(TIdentifier id);
    Task RemoveByPartitionAsync(TIdentifier id);
